name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
    - '**'


jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8']
        toxenv: [quality, docs, django40]

    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip
      run: pip install -r requirements/pip.txt

    - name: Install Dependencies
      run: pip install -r requirements/ci.txt


    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox

    #- name: Run coverage
    #  if: matrix.python-version == '3.8' && matrix.toxenv == 'django32'
    #  uses: codecov/codecov-action@v3
    #  with:
    #    flags: unittests
    #    fail_ci_if_error: true
  react_lint:
    name: Node.js linter
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node-version: [18]

    steps:
    - uses: actions/checkout@v3
    - name: Setting up Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install yarn
      run: npm install --global yarn

    - name: Install Node.js 18 dependencies
      run: yarn install

    - name: Run Node.js lint
      run: yarn lint
